# usermod -aG docker gitlab-runner

stages:
  - build
  - deploy

variables:
  PROJECT_NAME: zixun/zixun-manage
  REGISTRY_URL: registry.yizhiwechat.com

cache:
  key: nodemodules-$CI_COMMIT_REF_NAME
  paths:
    - node_modules/

build_develop:
  stage: build
  cache:
    key: nodemodules-$CI_COMMIT_REF_NAME
    paths:
      - node_modules/
  script:
    - rm -rf ./node_modules/
    - npm run bootstrap
    - rm -rf ./dist/
    - npm run build:test
    - rm -rf /opt/yitui-dev/web/zixun-manage/dist/
    - cp -rf ./dist/ /opt/yitui-dev/web/zixun-manage/dist/
  only:
    - develop
  tags:
    - yitui-runner-dev

# build_pre_release:
#   stage: build
#   cache:
#     key: nodemodules-$CI_COMMIT_REF_NAME
#     paths:
#       - node_modules/
#   script:
#     - rm -rf ./node_modules/
#     - npm run bootstrap
#     - rm -rf ./dist/
#     - npm run build:pre
#     - docker build . -t $PROJECT_NAME
#     - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_NAME
#     - docker push $REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_NAME
#   only:
#     - pre-release
#   tags:
#     - yitui-runner-prod
build_master:
  stage: build
  cache:
    key: nodemodules-$CI_COMMIT_REF_NAME
    paths:
      - node_modules/
  script:
    - rm -rf ./node_modules/
    - npm run bootstrap
    - rm -rf ./dist/
    - npm run build
    - docker build . -t $PROJECT_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:latest
    - docker push $REGISTRY_URL/$PROJECT_NAME:latest
  only:
    - master
  tags:
    - yitui-runner-prod

# deploy_pre_release:
#   stage: deploy
#   script:
#     - curl https://cs.console.aliyun.com/hook/trigger?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVySWQiOiJjNDM3YzAxNGZhOTZiNGQ3YThmYmRjYjZjNDYwZmE1MTciLCJpZCI6IjE0MTc1MyJ9.BipuvOzW2VDG4EEdEEllzEQSBobhf-a4m0rGk0iVy9xmNB79nOKs5qGjMjxz4u2dbMOL7cwppWoC4bzcdRk10Y3gqSfWqrgpRiUD1rArcJBzKreoh7AIrq-XmZbhF8Xzqb0ZlAbmL0D5KP0qMqnbBWnFKbfz_2icjDkpV_R3M_0
#   only:
#     - pre-release
#   tags:
#     - yitui-runner-prod
deploy_master:
  stage: deploy
  script:
    - curl https://cs.console.aliyun.com/hook/trigger?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVySWQiOiJjZDljMDM3ODM3N2RlNDcxYTg3ZTMwZjUyNTgyODA4NGQiLCJpZCI6IjIzMDEwMiJ9.EwAkpf5-oYLCY5drR2SMuiIrL_iKDkKjUK1t8oQPI3WLc4_JxSpnY0wlc_lYMcz-i4wkux7cHSXeys-wcS9XMHum69xeTVieT4bphuaB6TjETI7DzBSh7IapVd5ieSG2NBw9ZTtSmXp9wgnxo15jTDbda8oY0xEGdU3vpXI2Nag
  only:
    - master
  tags:
    - yitui-runner-prod
